### ISSUE TITLE
[Bug]: Custom icon settings cannot work

### ISSUE THREAD

**Issue by reg-chen** [timokoessler/2FAGuard#18]
### What happened?

Custom icon settings cannot work.
After I set a custom icon, it is still the default icon.

### What version of Windows are you using?

Windows 11 22631

### What version of the app are you using?

1.3.0.0 (Microsoft Store)

**Comment by timokoessler** [comment]
Thanks for opening an issue. What file type are you choosing as a icon? Does this happen with different images?

**Comment by reg-chen** [comment]
I have tried .png , .svg , .jpg.


https://github.com/timokoessler/2FAGuard/assets/34430957/a13ce9c2-f180-4754-bd9d-cd4e1daa6b8a

**Comment by timokoessler** [comment]
Sadly I cannot reproduce this problem. Does this also happen if you use the portable or classic installation edition of 2FAGuard? If so, does the `%LOCALAPPDATA%\2FAGuard\icons` folder contain any images or the folder `%LOCALAPPDATA%\2FAGuard\logs` any error logs?

Please note: The portable installation saves the data in the same folder and not in AppData.

**Comment by reg-chen** [comment]
I'd tired classic installation edition of 2FAGuard.
Same issue, but the %LOCALAPPDATA%\2FAGuard\icons folder contains my selected image file.
![圖片](https://github.com/timokoessler/2FAGuard/assets/34430957/d60e55f2-cd00-4f9b-85ab-58c2bdec1a8f)
There's no error log.

**Comment by timokoessler** [comment]
The error was that when I checked whether the logo file still existed, I took the path of a Uri object in which spaces were encoded. As your Windows user folder contains spaces, you have encountered the error. I will publish a new release with a fix soon.
