### ISSUE TITLE
Missing all Microsoft icons in main branch

### ISSUE THREAD

**Issue by Cristian9828** [timokoessler/2FAGuard#22]
### What happened?

Hello,
I tried to compile the project locally, it all worked successfully.
Found a problem: the icons list file under Guard.WPF/Assets/Icons/si.json is older than what I can see downloading the official product! For example, I tried to add a Microsoft Token and I can't find the right icon, but in the downloaded program I can find it!

Let me know if you can update this!
Thank you very much!
Fantastic product by the way, really appreciated!

### What version of Windows are you using?

11

### What version of the app are you using?

1.3.1

**Comment by timokoessler** [comment]
Hello,
Thanks for opening this issue. The repo contains the latest version of Simple Icons (v13.1.0).
I didn't even realise that the icons were missing and I have to admit that I didn't read the Simple Icons changelog during the last update. Now I found this pr https://github.com/simple-icons/simple-icons/pull/10019 that is removing all Microsoft Icons for legal reasons. I hope that Simple Icons will include them again in the future. Maybe I am going to downgrade it before the next release.
