### ISSUE TITLE
Application disappears after locking it from the right click on reduced icon

### ISSUE THREAD

**Issue by Cristian9828** [timokoessler/2FAGuard#24]
### What happened?

Hi,
I tried to lock the program using right click on reduced icon and the application disappeared. I wasn't able anymore to reach it from the applications bar.
I think the function works well, because if I try it with the tool open, it locks with password correctly. But when I try to reduce it, can't see it anymore.
Trying to open it again, gives me the error "This app can only be executed once at a time". So, checking on Task Manager, can find it and shutting it down permits to correctly re-open 2FAGuard.

Let me know if you can correct this!
Thank you very much

### What version of Windows are you using?

11

### What version of the app are you using?

1.3.1.0

**Comment by timokoessler** [comment]
Thanks for reporting this bug, I will fix it.
