### ISSUE TITLE
[Feature Request]: Keyboard copy support

### ISSUE THREAD

**Issue by jdunham22** [timokoessler/2FAGuard#29]
### What is your idea?

I can use <tab> to navigate through the GUI, but once a token has focus, I couldn't find a way to get the token into the clipboard without a mouse click.  It would be great to map enter and/or spacebar to copy the key.  People might also want to assign hotkeys but I'd be fine with just tab/enter navigation.

**Comment by timokoessler** [comment]
The following keyboard shortcuts will be available in the next release:
- `Enter`, `Space` or `C`: Copy the selected token
- `Q`: Show QR code
- `E`: Edit token
- `DEL`: Delete token
