### ISSUE TITLE
[Feature Request]: Smooth Scrolling?

### ISSUE THREAD

**Issue by CaptechOmar** [timokoessler/2FAGuard#31]
### What is your idea?

Could we have smooth scrolling when scrolling through the app?
It feels laggy trying to scroll through the items.

**Comment by timokoessler** [comment]
Hello CaptechOmar,
I haven't yet found a working solution that offers a proper smooth scrolling experience without having a major negative impact on performance. But I wouldn't call it laggy either. Do you have a very large number of tokens?

**Comment by CaptechOmar** [comment]
I don't know if it's a large number or not tbh but I have about 30 tokens.
You're right though, It's not laggy but it's not very smooth.
It's just that when I used it I thought, an app with such a very good design must have a better scrolling animations.

**Comment by timokoessler** [comment]
I'm going to close this topic, as I can't see any way to make the scrolling really noticeably better at the moment, without having a major impact on performance. This seems to be a general issue with WPF.
