### ISSUE TITLE
Bug: Login with Windows Hello fails (not always)

### ISSUE THREAD

**Issue by XDragonJrX** [timokoessler/2FAGuard#33]
### What happened?

When using Windows Hello PIN to login, it results in a 'Decryption Error (null)' warning.

It does work as expected on occasion, and the PIN being used is correct.

This is using the Windows Portable version if that helps. 

![Uploading Screenshot 2024-09-10 at 11.50.31 am.png…]()

### Provide the error message / stack trace

2024-09-10 10:07:57.817 +10:00 [WRN] Aptabase: Failed to perform TrackEvent due to "BadRequest" and response body Future sessions are not allowed.
2024-09-10 09:55:19.034 +10:00 [ERR] Error during login setup: Decryption failed (null)
2024-09-10 11:44:04.236 +10:00 [ERR] Error during login setup: Decryption failed (null)
2024-09-10 11:50:24.819 +10:00 [ERR] Error during login setup: Decryption failed (null)

### What version of Windows are you using?

Windows 10 22H2 (Build 19045.4842

### What version of the app are you using?

1.4.0.0 (Portable)

**Comment by timokoessler** [comment]
Thanks for reporting a bug. I attempted to reproduce your issue and was unable to do so.
- Does the same problem occur when you try to use a new, clean installation of the portable or desktop application?
- Does the issue persist if you disable and enable Windows Hello in the Windows System settings (not in the app)?
- Have you always used the portable app on the same device or on different devices / with different Windows users?

**Comment by XDragonJrX** [comment]
Hi @timokoessler 
* clean install yes. the desktop application doesnt fit our needs at this time.
* disabing and re-enabling it in windows doesnt help woth the error (altho it does if used in the app)
* portable app yes, same device yes. it is being accessed by multiple users however (which may be the issue?)

**Comment by timokoessler** [comment]
Is the app used by multiple users at the same time? This can cause a whole bunch of issues. That's why a single user can also not open multiple instances of the app, but I didn't though about multi-user terminal servers. The easy solution is blocking that too, but then only a single user can use the app at the same time. I am not sure if the app can / will support multiple instances accessing the same dataset at the same time in the future.

**Comment by XDragonJrX** [comment]
Hi @timokoessler 
The app is used by multiple people, but only one instance and one access to the dataset is ever running at a time.
The Windows Hello PIN however only works for the person that disables and re-enables the Hello PIN sign in regardless of the number of instances.
Best regards

**Comment by timokoessler** [comment]
With the additional information provided and finally some time for testing, I managed to find and fix this bug. The next release (v 1.5.0) will contain this fix (c25bb81).
Thanks for your help.

**Comment by XDragonJrX** [comment]
Thanks so much for your help @timokoessler really appreciate you taking the time to both make and also address such a trivial issue 😁
