### ISSUE TITLE
Bug: Default window size is too big

### ISSUE THREAD

**Issue by jdunham22** [timokoessler/2FAGuard#34]
### What happened?

On both my windows 11 laptops, the app launches too big so the title bar is off-screen or on the secondary monitor so it's hard to move the window around. 
![image](https://github.com/user-attachments/assets/5f031f08-75b7-4cfe-8c32-163f389fed1e)
One laptop has a 1920x1280 and the one with the attached image is 2560x1440 with 200% text scaling (which is the Windows recommended setting). I'm not sure about the text scaling for the other one but it's probably the recommended level or one size bigger.

### What version of Windows are you using?

Windows 11

### What version of the app are you using?

v1.4.0.0 Desktop

**Comment by timokoessler** [comment]
Thanks for reporting another bug. Fixed in 3cd7224. Will try to make a release in the next days.
