### ISSUE TITLE
[Feature Request]: Autofocus on the "Search tokens" field

### ISSUE THREAD

**Issue by Unleash123** [timokoessler/2FAGuard#37]
### What is your idea?

Have the cursor already present in that field at startup, so I don't have to move the mouse to click in there before typing the first letters of the token I'm after.
Example: I launch the app, I start typing "Gi" and the token for Github shows straight away.

**Comment by timokoessler** [comment]
Nice idea, added it.

**Comment by Unleash123** [comment]
Thank you for that, for the fast replies - and for the app too obviously!
It looks and feels neat.

I left Authy 1.5 year go (when they announced they'd discontinue their desktop app), switched to ente Auth a little white (oversized design back when I tried + request for email/credentials, whyy) before changing to Tauthy (not bad but lost autofocus feature mentioned above + not much customisable).

First impressions here are very positive; I want to stay :-)
