### ISSUE TITLE
Black Icons reversed for dark mode

### ISSUE THREAD

**Issue by CaptechOmar** [timokoessler/2FAGuard#40]
### What is your idea?

Can you add the ability of some dark icons like github, notion, and github to reverse to the white color in dark mode to improve visibility?
Some apps like authenticator pro on android and ente auth support this feature.

**Comment by timokoessler** [comment]
Added in commit 07023fa8a729e52ed97cb31fce286d5ace47804c. The color of a icon is overwritten if it is too similar to the background color. This does not work for custom icons.
