### ISSUE TITLE
Bug: All tokens duplicate pressing F5 on main dashboard

### ISSUE THREAD

**Issue by Cristian9828** [timokoessler/2FAGuard#41]
### What happened?

Hi,
pressing F5 button on main dashboard, it duplicates all the tokens cards on every click.

Thank you!

### What version of Windows are you using?

11

### What version of the app are you using?

1.5.1.0

**Comment by timokoessler** [comment]
Thanks for reporting. This is an interesting bug, never tried pressing F5 in this app before 😅.
