### ISSUE TITLE
[Feature Request]: Syncing with Ente Auth?

### ISSUE THREAD

**Issue by CaptechOmar** [timokoessler/2FAGuard#46]
### What is your idea?

I don't know how far of a stretch this is (probably too far) but both apps are open source
if it was possible to make 2fa guard as the front end of the ente auth windows app 
that would be great as it would allow syncing between different devices while using that nice design of 2fa guard

**Comment by timokoessler** [comment]
Hello, thanks for your request.
This feature is out of the scope of this project. It would not only require a lot of work, but it could easily break due to changes in the storage libraries used by ente auth. You can export and import tokens manually from Ente auth to 2FAGuard and vice versa.
