### ISSUE TITLE
Support for Windows Server 2019 (Windows 10 1809)

### ISSUE THREAD

**Issue by PascalReintjensDSGF** [timokoessler/2FAGuard#47]
### What is your idea?

Because Windows 10 1809 is not supported, the App is unable to be installed on Windows Server 2019 which is based on 1809.
On Windows Server 2022 it works great via App-Installer - but since Server 2019 will still be used for quite some time at lots of companies, this prevents the usage for a larger userbase.

Is there any chance to get support for 1809 / Windows Server 2019?

Thanks in advance!

**Comment by timokoessler** [comment]
Thanks for opening a feature request.
I already closed a issue about this (#3), but you have a better reason why 2FAGuard should support older Windows versions. There was a reason why I chose this minimal version, but I can't remember it anymore 😂. I will check the Microsoft changelogs again and come back to you then. Would you be willing to test a beta version on Windows Server 2019 and report whether everything works as expected?

**Comment by PascalReintjensDSGF** [comment]
Thank you very much for considering the support.
Yes, I would be willing to test a beta version on Windows Server 2019 and report back :)

**Comment by PascalReintjensDSGF** [comment]
Hello @timokoessler - did you have any time to check the Microsoft changelogs? Thanks in advance.

**Comment by timokoessler** [comment]
Hello Pascal,
Unfortunately I don't have much time at the moment, so I apologise for the delay. You can download a signed test installer using the following link. It would be nice if you could especially test features like Windows Hello or the detection of QR codes on the screen. You mentioned the App-Installer, may I ask why you prefer using MSIX? 

https://2faguard.app/static-content/2FAGuard-Installer-1.5.2-Test.exe

**Comment by timokoessler** [comment]
Interesting. The message "Dieses Programm unterstützt die auf Ihrem Computer installierte Version nicht." is displayed by the OS and not by the app itself, or? Because I don't find any relevant search results with this exact text. I set the minimum OS version of the app to `10.0.17763.0`. I will try to check this in a VM in the next days.

**Comment by PascalReintjensDSGF** [comment]
This is the message that appears:
![388884910-156f9907-a857-4858-a22b-1dc69494e43a](https://github.com/user-attachments/assets/aa3fa6e7-2c13-4ca9-927e-56c3b7e33bf4)

As soon as you double click the exe linked by you, Windows asks whether you want to install for yourself or all users, and after you select an option, the message appears.

Could it be that the installer has it's own version number check that can differ from the one you set?

Otherwise, here are some regkeys and values that show the different ways Windows Server 2019 names its own version:
![Infos](https://github.com/user-attachments/assets/98901040-1e90-42d5-9047-426653beeb83)

**Comment by timokoessler** [comment]
Sorry, that's my fault! I totally forgot that the software I use to build the installer also has a option for the minimum OS version.

A new link: https://2faguard.app/static-content/2FAGuard-Installer-1.5.2-WinServer19-Test.exe

**Comment by PascalReintjensDSGF** [comment]
Thank you very much - the installation now worked without any problems. 
I have already tested a little and at first glance 2FAGuard seems to work great.
I will test as much as possible in the beginning of the coming week and then give more feedback.

However, I have already noticed one problem that I wanted to give as feedback as soon as possible:
When I open 2FAGuard with one user on the server and then try to open it with a second user on the same server at the same time, 2FAGuard doesn't start for the second user. As soon as the first user has closed 2FAGuard, the second user then is able again to open 2FAGuard.
When one user is already using 2FAGuard and you try to open it on the second user, you can see in the task manager that its background processes are started for the second user for a moment and then they stop themselves before 2FAGuard becomes visible.
I am guessing that the program is checking whether 2FAGuard is already running, and that that check isn't designed for windows server where different users could start the same program in their own context at the same time.

**Comment by timokoessler** [comment]
Nice that you can run it! This issue is hopefully fixed with this new version 😅.
https://2faguard.app/static-content/2FAGuard-Installer-1.5.2-WinServer19-Test-3.exe

**Comment by timokoessler** [comment]
Cool. Thanks for your detailed report! I will keep this issue open until the next release. Regarding the system theme I am not even sure if it's a issue related to Windows Server or to this old Windows version.
