### ISSUE TITLE
[Feature Request]: Adapted to Stratum

### ISSUE THREAD

**Issue by Master-Panda** [timokoessler/2FAGuard#49]
### What is your idea?

Authenticator is obsolete. There is now a newer Stratum. The backup files of the two are different. Please adapt to the new Stratum.
When adding a token, scan the QR code through the computer's camera, which is more convenient.
The representation of the remaining time for token renewal is not perfect. Remove the circle on the right and replace it with a gradually shorter line segment below, like Stratum.
Anyway, thank you for your hard work

**Comment by timokoessler** [comment]
Hello. Thanks for opening an issue!
The backup format is the same, only the file extension changed. As a workaround you can simply change the file extension of a backup file to `.authpro`. The next release will include a rename to Stratum.

Currently scanning codes with the camera is not planned. If you really like to see this feature included, please open a separate issue and explain your use case / why you want to scan TOTP QR codes with your laptop camera.
