### ISSUE TITLE
[Feature Request]: Ideas for enterprise "settings" (regkeys)

### ISSUE THREAD

**Issue by PascalReintjensDSGF** [timokoessler/2FAGuard#52]
### What is your idea?

Below are two ideas for regkeys / enterprise settings, that would be really helpful for some companies and hopefully easy to implement:

![image](https://github.com/user-attachments/assets/611ff42c-22d2-48cc-8a5d-ef8b355622ad)
Setting this regkey would result in 2FAGuard using the specified folder as savefolder for its configuration / database files instead of \appdata\local. 
This path should be able to be an UNC path and be able to include a placeholder for the username (for example %username%)
I am hoping this is easy to implement, since there already is a pocket edition which changes the savepath to it's current folder.

----------------------------

![image](https://github.com/user-attachments/assets/81a0857c-192d-4017-9bfe-72f4e088ccd5)
These three regkeys would hide the corresponding option in the Setup-UI when they exist and are set to a value of one.
- Setting one of these keys results in a hidden button of the corresponding option.
- Setting two of these keys prompts the UI to skip the selection and directly opens the last option remaining **(this is quite helpful, since normal company users then don't have to choose an option, which could be a possible hurdle for some users)**
- Setting all three of these keys should result in the UI not hiding anything, since this would be clearly a configuration fault.

**Comment by timokoessler** [comment]
Hi Pascal,
You can download a new test installer using the following url: https://2faguard.app/static-content/2FAGuard-Installer-1.5.2-Test-WinServer-4.exe. All currently available keys can be found in [this markdown file](https://github.com/timokoessler/2FAGuard/blob/main/docs/advanced.md).

**Comment by PascalReintjensDSGF** [comment]
Hello Timo,
I now tested all regkeys, and they work great. Thank you very much!

| Regkey | Works? | Comment |
| --- | --- | --- |
|Modified AppDataPath |✓||
|Modfied AppDataPath with UNC-Path and %USERNAME%|✓||
|Setup > HideSkip |✓||
|Setup > HideWinHello |✓||
|Setup > HidePassword |✓||
|Setup > Hide two Options|✓|Results in remaining option automatically being openend|
|Settings > HideWinHello |✓||
|Settings > HidePreventRecording  |✓||
|Settings > HideSecurityKey  |✓||
