### ISSUE TITLE
Bug: Backup Import Issues and Outdated Name Reference in 2FAGuard

### ISSUE THREAD

**Issue by gh0stsp3ctre** [timokoessler/2FAGuard#53]
### What happened?

I encountered issues while importing a backup in 2FAGuard. The app still references the outdated name "Authenticator Pro" instead of "Stratum" in its UI. Additionally, the app fails to recognize .stratum backup files and instead expects .authpro files, which causes the import process to fail unless the file extension is manually renamed.

Bug:
1. The app refers to "Authenticator Pro" instead of "Stratum."
2. The app does not recognize .stratum files for backup import.

Expected Behavior:
1. The app should reflect the updated branding and refer to "Stratum."
2. The app should accept .stratum files without requiring a manual file extension change.

How can we reproduce the problem?
1. Open 2FAGuard.
2. Attempt to import a .stratum backup file created in Stratum.
3. Observe the import failure.
4. Rename the .stratum file to .authpro and retry the import to verify functionality.

Website: https://stratumauth.com/
Github: https://github.com/stratumauth/app

Why they changed name from Authenticator Pro to Stratum:
https://www.reddit.com/r/WearOS/comments/1fgm9b8/open_source_authenticator_pro_is_no_longer_on_the/

### Provide the error message / stack trace

No specific error message was displayed, but the import process fails until the file extension is renamed from .stratum to .authpro.

### What version of Windows are you using?

Windows 11 Pro - 24H2 -  OS Build: 26100.2314

### What version of the app are you using?

1.5.1.0

**Comment by timokoessler** [comment]
Thanks for reporting. This has already been changed (see https://github.com/timokoessler/2FAGuard/issues/49), but is not released yet.
