### ISSUE TITLE
Bug: Language keeps resetting

### ISSUE THREAD

**Issue by iannacone** [timokoessler/2FAGuard#55]
### What happened?

When setting the software language and closing and re-opening the window, the language seems to be set back to the default value (system) even if it looks that it is differently selected.

### What version of Windows are you using?

Windows 11 Business 23H2 22631.4317

### What version of the app are you using?

1.5.2.0

**Comment by timokoessler** [comment]
Thanks for reporting, will fix asap.

**Comment by timokoessler** [comment]
Version 1.5.3 has now been released and the update is being rolled out. Please note that it may take up to two days for the update to be available in the Microsoft Store. I will leave this issue open until then.

**Comment by iannacone** [comment]
Klasse
